import { IMAGES } from "./images";

export const DEMO_PROMPTS = [
  {
    id: 1,
    name: "A haunted Victorian mansion with flickering candlelight, cobwebbed chandeliers, and ghostly figures in the windows, set on a misty night.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 2,
    name: "A fog-covered graveyard at midnight with crumbling tombstones, twisted trees, and a looming full moon casting eerie shadows.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 3,
    name: "An abandoned carnival in the middle of nowhere, with broken rides, torn clown posters, and a creepy funhouse in the background.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 4,
    name: "A cursed forest clearing surrounded by crooked trees, with jack-o’-lanterns glowing ominously and eerie fog swirling around the ground.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 5,
    name: "A dilapidated witches' cottage deep in the woods, filled with glowing potions, a bubbling cauldron, and enchanted objects floating in the air.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 6,
    name: "A spooky, deserted town square with creaky wooden signs, shattered windows, and Halloween decorations blowing in the wind.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 7,
    name: "A full moon-lit swamp with murky waters, ancient gnarled trees, and the faint glow of ghostly will-o'-the-wisps above the surface.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 8,
    name: "An eerie pumpkin patch at dusk, with overgrown vines, massive pumpkins, and scarecrows with sinister grins guarding the area.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 9,
    name: "A creepy attic filled with dusty antiques, forgotten toys, and the silhouettes of ghosts passing through the cobweb-filled rafters.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 10,
    name: "A gothic cathedral in ruins, with shattered stained glass windows casting rainbow shards on the ground, and crows circling overhead.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 11,
    name: "A shadowy cave entrance with bats flying out, ancient symbols carved into the rocks, and glowing eyes staring out from the darkness within.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 12,
    name: "A stormy night in a coastal town, with waves crashing against a rocky shore, a haunted lighthouse blinking in the distance, and lightning illuminating the sky.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 13,
    name: "A cursed library with shelves of ancient, leather-bound books, floating specters, and enchanted candles flickering in the dim light.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 14,
    name: "A misty castle courtyard surrounded by tall, dark towers, with ghostly knights standing guard and a massive iron gate creaking open.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 15,
    name: "An enchanted, eerie forest with trees made of twisted bones, glowing mushrooms, and the faint outline of ghostly creatures drifting through the fog.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 16,
    name: "An ancient crypt with crumbling stone walls, rows of skeletons lying in open coffins, and flickering torches lining the halls.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 17,
    name: "A spooky, abandoned hospital with broken windows, rusted medical equipment, and mysterious bloodstains leading down dark hallways.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 18,
    name: "A cursed pirate ship drifting on a foggy sea, with torn sails, a ghostly crew, and treasure chests filled with cursed gold glowing with an eerie light.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 19,
    name: "A haunted amusement park at night, with an eerie Ferris wheel, derelict bumper cars, and the distant echo of a creepy carousel music.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 20,
    name: "A moonlit, foggy street in an old Victorian city, with gas lamps flickering, shadowy figures lurking in alleyways, and ghostly carriages passing by.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 21,
    name: "A witch's ritual circle deep in the woods, surrounded by glowing runes, skulls, and candles, with the ghostly outline of witches performing a dark spell.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 22,
    name: "An eerie, overgrown cemetery with ivy-covered tombs, ancient mausoleums, and skeletal hands rising from the ground in the foggy distance.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 23,
    name: "A haunted cabin in the woods, with broken windows, creaky wooden floors, and mysterious shadows moving just beyond the walls.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 24,
    name: "A creepy, abandoned church with cracked stained-glass windows, twisted vines overtaking the altar, and shadowy figures lurking in the pews.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 25,
    name: "A floating haunted island above a dark sea, with jagged cliffs, eerie winds, and a twisted, abandoned lighthouse glowing in the distance.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 26,
    name: "A dark, enchanted forest with swirling fog, gnarled trees, glowing runes carved into the trunks, and distant, glowing eyes watching from the shadows.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 27,
    name: "A werewolf transformation scene in a misty forest clearing, with a rising full moon, torn clothes scattered on the ground, and claw marks on the trees.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 28,
    name: "A vampire's lair in a crumbling gothic castle, with velvet curtains, ancient portraits, and flickering candelabras casting long shadows on the stone walls.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 29,
    name: "A mysterious, glowing portal in the middle of a dark forest, with swirling mist, ancient runes, and ghostly figures stepping through the doorway.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 30,
    name: "An eerie, abandoned doll factory with broken, lifeless dolls scattered around, creaky conveyor belts, and distant echoes of mechanical sounds.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 31,
    name: "A twisted circus tent in the middle of a foggy field, with ripped fabric, eerie clown faces painted on the walls, and dimly lit lanterns hanging from above.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 32,
    name: "A haunted farmhouse at sunset, with a scarecrow in the field, a broken-down tractor, and shadowy figures moving inside the house.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 33,
    name: "A shadowy crypt entrance built into a mountainside, surrounded by fog and ancient statues of gargoyles watching over the path leading in.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 34,
    name: "A witch's apothecary shop with shelves full of mysterious potions, glowing crystals, enchanted herbs, and a large cauldron bubbling in the corner.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 35,
    name: "A creepy, abandoned subway station deep underground, with flickering lights, old graffiti, and ghostly passengers waiting on the platform.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 36,
    name: "An enchanted pumpkin patch at midnight, with pumpkins glowing from within, vines writhing like snakes, and scarecrows coming to life.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 37,
    name: "A spooky, fog-filled corn maze at dusk, with dark shadows lurking between the tall corn stalks, and a faint, eerie glow coming from the center.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 38,
    name: "A haunted, stormy beach at night, with shipwrecks half-buried in the sand, glowing ghostly figures walking along the shore, and lightning flashing over a distant lighthouse.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 39,
    name: "A Halloween town square, with jack-o'-lanterns lining the streets, old, creaky houses, and townsfolk in eerie costumes celebrating under a full moon.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 40,
    name: "A creepy, fog-covered bridge crossing over a dark river, with shadowy figures standing on the far side, and bats flying through the air.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 41,
    name: "An ancient haunted temple hidden deep in a jungle, with overgrown vines, glowing mystical symbols, and ghostly spirits guarding the entrance.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 42,
    name: "A cursed carnival sideshow, with flickering lights, broken-down rides, and eerie carnival music playing in the background as ghostly performers walk by.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
  {
    id: 43,
    name: "A twisted, haunted mansion garden, overgrown with thorny vines, statues with cracked faces, and strange, ghostly figures floating among the shadows.",
    originalImageUrl: IMAGES.pumpkin,
    type: "prompt",
  },
];
